run:
  timeout: 5m
  tests: true
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - govet
    - bodyclose
    - errorlint
    - sloglint
    - sqlclosecheck
  disable:
    - typecheck

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
  gocritic:
    enabled-checks:
      - ifElseChain
      - sloppyReassign
      - unnecessaryDefer
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
        - dupl
    - path: "docs/.*"
      linters:
        - gofmt
        - revive
  max-same-issues: 0

output:
  format: colored-line-number
